const promiseFive = new Promise((resolve, reject) => {
//   setTimeout(() => {
//     let error = true;
//     if (!error) {
//       resolve({ userName: "rahul", password: "123" });
//     } else {
//       reject("error something went wrong");
//     }
//   }, 1000);
// });

// async function consumePromiseFive() {
//   try {
//     const res = await promiseFive;
//     console.log(res);
//   } catch (error) {
//     console.log(error);
//   }
// }